### PR TITLE
Allow overriding of _routeToRegExp

### PR DESCRIPTION
**Pull request by kalley**

### CODE REVIEW

**Comment by aeksco** [comment]
:+1:

What's the use case? Just curious :)

**Comment by kalley** [comment]
We are doing case-insensitive routes. But if someone wanted camelCase to map to snake_case or something, that could also be a valid reason.

**Comment by aeksco** [comment]
@kalley Nice! Solid addition :D

**Comment by kalley** [comment]
Just rebased, so you should be able to merge it.

**Comment by existentialism** [comment]
@aeksco once rebased, any issues with merging this?

**Comment by kloy** [comment]
@aeksco Is there a reason this has not been merged?

**Comment by aeksco** [comment]
@kloy Apologies for the delay! All looks good to merge, though it seems I don't currently have write access. I'll look into getting that squared away this evening so we can get this merged in - I'll keep you posted!

**Comment by aeksco** [comment]
@kloy Got write access - PR 48 merged.

**Comment by kloy** [comment]
Whoohoo! Thank you!

**Pull request merged**
